// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whxdvpwtlyosybawmwhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoeGR2cHd0bHlvc3liYXdtd2h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzg3NDgsImV4cCI6MjA2OTYxNDc0OH0._Nn7Nu7lWrfEpC6w6IwvALDW5_I7Tn0q0uz8HMemLtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});